development:
  adapter: postgresql
  database: iyd
  # host: localhost
  port: 5432
  username: postgres

test:
  adapter: postgresql
  database: iyd
  # host: localhost
  port: 5432
  username: postgres

production:
  adapter: postgresql
  database: iyd
  # host: localhost
  port: 5432
  username: postgres